### ISSUE TITLE
Suggested updates to README

### ISSUE THREAD

**Issue by 6a6d74** [OpenWIS/openwis#231]
In ISSUE #228 @rogers492 suggests linking the OSS package to the [README](openwis/README.MD) file. +1 to that idea, _but_ in looking at the README I notice a couple of things that need to be changed.

1) [Line 3](https://github.com/OpenWIS/openwis/edit/master/README.MD#L3) there's a link to a description of the WIS at GISC Melbourne. Inclusion of this information is a good idea. Could we insert the details locally into the README rather than linking out to an external website?

2) The [Copyright and License](https://github.com/OpenWIS/openwis/edit/master/README.MD#L204-208) section currently states:

> OpenWIS® is free software: you can redistribute it and/or modify it under the terms of the License specified for each OpenWIS® Project (see `[LICENSE](./LICENSE)`).

Looks like this has been updated to reflect that each project may choose its own license from the OSS list - which is good. But we've lost the clarity that _this_ project uses GPL3. Suggest the following:

> OpenWIS® is free software: you can redistribute it and/or modify it under the terms of the License. In accordance with [TITLE 9: SOFTWARE LICENSING](http://openwis.github.io/openwis-documentation/rules/9-software-licensing.html) from the [Internal Rules of the OpenWIS Association AISBL](http://openwis.github.io/openwis-documentation/rules/), each OpenWIS® Project must specify a [license approved by the Open Source Initiative](https://opensource.org/licenses/). This Project is licensed under the the `[GNU General Public Licence, version 3.0](./LICENSE)`.

**Comment by rogers492** [comment]
Since the text on the Melbourne About-Page includes general references to OpenWIS and specific references to Melbourne GISC, I have used the more general text that Exeter, Toulouse and Washington all have in common:
OpenWIS is an implementation of the WMO Information System.

The World Meteorological Organization (WMO) has been working for several years towards upgrading its global infrastructure to support all of its international programmes of work, both operational and research-based, to collect, share and disseminate information. The new infrastructure is called the WIS, the WMO Information System, and identifies three top-level functions. These are:

GISC: Global Information System Centre;
DCPC: Data Collection and Production Centre;
NC: National Centre.
All three functions contribute to the circulation of priority data, system wide security, monitoring and implementation of WMO data policies. GISCs and DCPCs allow the Discovery Access and Retrieval of data, products and services offered by WIS Centres, but GISCs offer a global view of this information and provide distributed and resilient access to critical data and products.

OpenWIS aims to perform the three functions required by the WMO Information System that is, GISC, DCPC and NC.

**Comment by rogers492** [comment]
I have updated the Copyright ans License section almost exactly as @6a6d74 suggests.

**Comment by rogers492** [comment]
Hi @adrian-wood : Would you please merge PRs #245 and #246 and then close this issue. ta, Paul

**Comment by rogers492** [comment]
This information has now been put into the READMEs for v3 and v4 - issue closed.
