### ISSUE TITLE
OpenWIS HTTPs Portal Logout Failure

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/openwis#285]
Portal logout fails when OpenWIS is deployed using an HTTPs proxy.   The HTTPs proxy is implemented according to the OpenWIS-3.14 deployment guide section 7.5.7.   The portal login process is successful, only the Logout process fails.

> TokenUtilities.java: ERROR: Error during logout process - Error during test if token is valid : Fatal transport error.

The logout process fails on two accounts:
  1. The browser cookie and SAML token are not purged.
  2. Security Service retains the session as "logged in".

![openwis https logout issue](https://user-images.githubusercontent.com/15819390/40315221-c20820f4-5ce8-11e8-8264-880aca137381.png)

**Comment by mgiannoni** [comment]
We have not consistently reproduced the error in the screen-shot, however the browser state remaining logged in is consistent.   Further examination is needed.

**Comment by zhangz555** [comment]
I give it a try on the admin portal and solve the issue. Now the behavior is desirable: each time after a user logout and then re-login, he is redirected to openam for username/password; there is no more automatic re-login.  

The approach I take is clearing off the residing session info on the client side after a user logout. The key lies in a package named "org.openwis.metadataportal.services.login" and the  "org.openwis.metadataportal.services.login.logout" class. I modify the code there, so that each time a user logout, the HTTP servlet response will clear off the residing session info, thus forcing the user to re-enter name/password to openam when he tries re-login.

**Comment by zhangz555** [comment]
I tested this on the user portal. It appears that the behaviour on the user portal is desirably the same as it is on the admin portal now: each time after a user logout and then re-login, he is redirected to openam for username/password; there is no more automatic re-login.

I will create a pull request for this change.

**Comment by zhangz555** [comment]
The pull request is created. See here https://github.com/OpenWIS/openwis/pull/298
