### ISSUE TITLE
3.14.9 compiling failure

### ISSUE THREAD

**Issue by yvesgoupil** [OpenWIS/openwis#324]
The 3.14.9 Openwis version does not compile anymore on Travis and locally on my CentOS7 VM since the beginning of april.
There are missing geotools and opengis depencies for openwis-portal-solr.  

See error on Travis Build #137 : https://github.com/OpenWIS/openwis/wiki

The error locally is :   
` Failed to execute goal on project openwis-portal-solr: Could not resolve dependencies for project io.openwis.metadataportal:openwis-portal-solr:war:3.14.8-SNAPSHOT: The following artifacts could not be resolved: org.opengis:geoapi-pending:jar:2.3-M1, org.geotools:gt-api:jar:2.6.2, org.geotools:gt-main:jar:2.6.2, org.geotools.xsd:gt-xsd-core:jar:2.6.2, org.geotools.xsd:gt-xsd-gml3:jar:2.6.2, org.geotools:gt-postgis:jar:2.6.2, org.geotools:gt-shapefile:jar:2.6.2, org.opengis:geoapi:jar:2.3-M1, org.geotools:gt-epsg-hsql:jar:2.6.2, com.vividsolutions:jts:jar:1.10, org.geotools.xsd:gt-xsd-filter:jar:2.6.2: Could not find artifact org.opengis:geoapi-pending:jar:2.3-M1 in jboss-maven2 (https://repository.jboss.org/nexus/content/groups/public-jboss) -> [Help 1]`

**Comment by zhangz555** [comment]
Yes，I have done some investigation here, and find that the repo serving all these artifacts are not available anymore. I will share details. —Zhan

**Comment by zhangz555** [comment]
The real remote repo that holds the artifacts is NOT the one stated in the
compile error message.

See the attachment and highlighted texts therein. That is the complained
dependency in the build. The repo is called "OSGeo Old", which url is
https://download.osgeo.org/webdav/geotools/. Point to there, you will get
404, which means that this remote repo is NOT available anymore. --Zhan
[image: image.png]

**Comment by zhangz555** [comment]
I just did some experiments to see how many artifacts we probably have lost due to repo closure. Since I know that org.opengis:geoapi-pending does not have version 2.3-M1, but it still has version 3.1-M01, so I changed its version to 3.1-M01. This is what I get when doing a build

[ERROR] Failed to execute goal on project openwis-portal-solr: Could not resolve dependencies for project io.openwis.metadataportal:openwis-portal-solr:war:3.14.8-SNAPSHOT: The following artifacts could not be resolved: org.geotools:gt-api:jar:2.6.2, org.geotools:gt-main:jar:2.6.2, org.geotools.xsd:gt-xsd-core:jar:2.6.2, org.geotools.xsd:gt-xsd-gml3:jar:2.6.2, org.geotools:gt-postgis:jar:2.6.2, org.geotools:gt-shapefile:jar:2.6.2, org.opengis:geoapi:jar:2.3-M1, org.geotools:gt-epsg-hsql:jar:2.6.2, org.geotools.xsd:gt-xsd-filter:jar:2.6.2: Failure to find org.geotools:gt-api:jar:2.6.2 in https://repository.jboss.org/nexus/content/groups/public-jboss was cached in the local repository, resolution will not be reattempted until the update interval of jboss-maven2 has elapsed or updates are forced -> [Help 1]

We can see that there is no complaining for org.opengis:geoapi-pending anymore. However, new complaints of unavailable artifacts appear. This experiment somehow reveals that we may have lost quite some artifacts due to the repo closure.

**Comment by zhangz555** [comment]
We need to find a solution to solve this issue. The ultimate goal should be replacing opengis/geotools with more recent versions. 

In the mean time, we can have a plan of using cached artifacts in the local repository in the MDL server to serve the OpenWIS community. To accomplish this, we need to upload the cached artifacts to the OpenWIS codebase in github; setup a mechanism to let the build process utilize them; and try to minimize travis CI script changes due to this importation effort.

**Comment by zhangz555** [comment]
I will investigate detailed steps of importing artifacts one-by-one into OpenWIS in travis CI build and write them out and share here.

**Comment by zhangz555** [comment]
When validate the availability of other missing artifacts, I find that there are updates on mvnrepository.com website. I tracked the repo url and update some code in OpenWIS. Now OpenWIS can be successfully built without errors.

**Comment by zhangz555** [comment]
I plan to generate a pull request against master branch. I believe this will fix the failure of travis CI build. OpenWIS administrator, can you let me know whether master branch is the one that this fix should be pushed to?

**Comment by yvesgoupil** [comment]
I just made a compilation from scratch (without any pre-existing m2 repository) of your last openwis-3.14.10 version. The compilation works perfectly. Thank you, Zhan, for this upgrade action!

**Comment by solson-nws** [comment]
Yves:

Thanks for confirming!  Appreciate the feedback!

Steve

**Comment by solson-nws** [comment]
Closing this issue as it is resolved.
